import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/config/provider/theme.provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexProvider } from "@/config/provider/convex.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ConvexProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange

            >
              {children}
            </ThemeProvider>
          </ConvexProvider>

        </body>
      </html>
    

  );
}
